version: "3"
services:
  php:
    build: php/
    volumes:
      - ./html:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root


networks:
  default:
    external:
      name: my-bridge-network






