version: "3"
services:
  php:
    image: php:7.4-fpm
    volumes:
      - './homework/docker/html:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
      - './homework/docker/html:/var/www/html'
      - './homework/docker/nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root







