version: '3'
services:
    nginx:
        image: 'nginx:latest'
        ports:
            - 80:80
        volumes:
            - './:/var/www'
            - './nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - laravel_default
    db:
        image: mysql:8
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - laravel_default
    app:
        build:
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - ./:/var/www
        networks:
            - laravel_default




networks:
    laravel_default:
        driver: bridge


